######################################################################
# Automatically generated by qmake (2.01a) Wed Jun 4 21:40:07 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
